-- ensure aws_s3 helper and dependencies are installed
CREATE EXTENSION IF NOT EXISTS aws_s3 CASCADE;

-- ensure import target tables exist
CREATE TABLE IF NOT EXISTS simple_area_cell_assignment_raw (
    id INT PRIMARY KEY,
    marine_layer_id INT,
    area_id INT,
    fao_area_id INT,
    cell_id INT,
    water_area DOUBLE
);

CREATE TABLE IF NOT EXISTS allocation_simple_area (
    allocation_simple_area_id INT PRIMARY KEY,
    marine_layer_id INT,
    area_id INT,
    fao_area_id DOUBLE,
    is_active INT,
    inherited_att_belongs_to_reconstruction_eez_id INT,
    inherited_att_is_ifa INT,
    inherited_att_allows_coastal_fishing_for_layer2_data INT
);

CREATE TABLE IF NOT EXISTS cell (
    cell_id INT PRIMARY KEY,
    total_area DOUBLE,
    water_area DOUBLE
);

CREATE TABLE IF NOT EXISTS data (
    unique_area_id INT,
    universal_data_id INT,
    area_type TEXT,
    generic_allocation_area_id INT,
    original_fishing_entity_id INT,
    fishing_entity_id INT,
    catch_amount DOUBLE,
    catch_type_id INT,
    reporting_status_id INT,
    gear_type_id INT,
    input_type_id INT,
    sector_type_id INT,
    taxon_key INT,
    year INT,
    internal_audit_depth_function_override BOOLEAN
    allocation_area_type_id INT,
    data_layer_id INT
);

CREATE TABLE IF NOT EXISTS allocation_result (
    universal_data_id INT,
    allocation_simple_id INT,
    cell_id INT,
    allocated_catch DOUBLE
);

-- Note: further SQL will be generated by code and output to allocation_import.sql
